name: Deploy Vercel
description: Deploy Vercel in two modes

inputs:
  vercel-token:
    description: 'Vercel token'
    required: true
  mode:
    description: 'Deployment mode'
    required: true
    default: 'production'

runs:
  using: 'composite'
  steps:
    - name: Install Vercel CLI
      run: npm install --global vercel@canary
      shell: bash

    - name: PROD Vercel Deployment
      if: ${{ inputs.mode == 'production' }}
      run: |
        vercel pull --yes --environment=production --token=${{ inputs.VERC_TOKEN }}
        vercel build --prod --token=${{ inputs.VERC_TOKEN }}
        vercel deploy --prebuilt --prod --token=${{ inputs.VERC_TOKEN }}
      shell: bash

    - name: PREVIEW Vercel Deployment
      if: ${{ inputs.mode == 'preview' }}
      run: |
        vercel pull --yes --environment=preview --token=${{ inputs.VERC_TOKEN }}
        vercel build --token=${{ inputs.VERC_TOKEN }}
        DEPLOY_OUTPUT="$(vercel deploy --token=${{ inputs.VERC_TOKEN }})"
        DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep http | tail -n 1)
        echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
      shell: bash
