name: deploy website
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #  your build commands
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v25 #deploy
        with:
          vercel-token: 'ExWPNFZYHLILtLK4E8M9Ft0y' # Required ExWPNFZYHLILtLK4E8M9Ft0y
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: '--prod' #Optional
          vercel-org-id: 'mateusz.w.twardy@gmail.com'  #Required mateusz.w.twardy@gmail.com
          vercel-project-id: 'prj_TvGs6R1u1WugcFSqmgVdHn7mIG6a' #Required prj_TvGs6R1u1WugcFSqmgVdHn7mIG6a
          working-directory: ./sub-directory
