name: deploy website

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Checks out the repository code

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build # Builds the project using Vite

      - name: Vercel Deployment
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: 'ExWPNFZYHLILtLK4E8M9Ft0y' # Required ExWPNFZYHLILtLK4E8M9Ft0y
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: '--prod' #Optional
          vercel-org-id: 'mateusz.w.twardy@gmail.com'  #Required mateusz.w.twardy@gmail.com
          vercel-project-id: 'prj_TvGs6R1u1WugcFSqmgVdHn7mIG6a' #Required prj_TvGs6R1u1WugcFSqmgVdHn7mIG6a
          working-directory: ./sub-directory
